### ISSUE TITLE
Not working with multiple elements

### ISSUE THREAD

**Issue by CreditRepairConnection** [irfan/jquery-star-rating#10]
Thanks for this plugin. It's pretty simple and easy to use. I'm planning to use it for a project.
However, I noticed some issue.

If you initialize like this:
$(function(){                   // Start when document ready
    $('.star-rating').rating(); // Call the rating plugin
}); 

then, you have more than one star-rating class, it only works for the first child. 
Have you experience with this? Thanks.

**Comment by irfan** [comment]
I have tested again, it works as expected. Please don't forget to change name="foo" attributes of the radio input elements.

**Comment by CreditRepairConnection** [comment]
Really appreciate your response. Yeah, it works when the elements are ready on load. But, seems not working if the elements are generated through JS or cloned from other elements that has a star-rating class. And yes, I changed the attribute name value.

I'm wondering how would you handle that kind of scenario using your plugin? Do I need to re-initialize it?
