### ISSUE TITLE
Set amount of stars on page load?

### ISSUE THREAD

**Issue by sciascia** [irfan/jquery-star-rating#11]
Hi there,

Sorry for posting here as this isn't really an issue, but is there a way to set the rating to 5 stars on page load?

We're seeing a few people giving great reviews but forgetting to click the stars so end up with zero ratings.

Hope that makes sense.

Cheers

Ben

**Comment by CptMeatball** [comment]
I might be late to the party here, but you just need to check the ````input```` at five starts.

     <input type="radio" name="example" class="rating" value="5" checked />

**Comment by mackieee** [comment]
This should be in the Docs! x)
