### ISSUE TITLE
where's the licence file?

### ISSUE THREAD

**Issue by snowch** [irfan/jquery-star-rating#14]
What license does this project have?  Apache 2.0?

**Comment by irfan** [comment]
Hi @snowch Please see licence below, I'll add later on to the repository.
http://www.wtfpl.net/

```
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                Version 2, December 2004
```

 Copyright (C) 2004 Sam Hocevar sam@hocevar.net

 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

```
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
```

   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
1. You just DO WHAT THE FUCK YOU WANT TO.

**Comment by cgwhitehead** [comment]
HAHAHAHA This is my favorite license!
