### ISSUE TITLE
Sending information along

### ISSUE THREAD

**Issue by saadat99** [irfan/jquery-star-rating#17]
How can i send information for example id using this plugin?
Here is my form:
```
<td><?= $value['id'] ?></td>
<td><?= $value['name'] ?></td>
<td>
    <section class="star-rating" id="<?= $value['id'] ?>" >
        <input type="radio" name="example" class="rating" id="radio_1" value="1" />
        <input type="radio" name="example" class="rating" id="radio_2" value="2" />
        <input type="radio" name="example" class="rating" id="radio_3" value="3" />
        <input type="radio" name="example" class="rating" id="radio_4" value="4" />
        <input type="radio" name="example" class="rating" id="radio_5" value="5" />
    </section>
</td>
```

**Comment by mucahidcakmakdev** [comment]
You must send the information with a HTML form POST or with Ajax but using the attribute "name" of the input. : `<input type="radio" name="example" class="rating" id="radio_1" value="1" />`
here the value of attribute name is **"example"**

**Comment by saadat99** [comment]
> You must send the information with a HTML form POST or with Ajax but using the attribute "name" of the input. : `<input type="radio" name="example" class="rating" id="radio_1" value="1" />`
> here the value of attribute name is **"example"**

Thanks. So the name attribute should be the same as radio buttons. What do i need in Javascript part? Can you give me an example please?

**Comment by mucahidcakmakdev** [comment]
You can get the value of rating with Jquery : $('input[name="example"]').val();
and you can send the value with ajax to your php file.

**Comment by saadat99** [comment]
No that is not what i meant. Let me explain again.
```
    <section class="star-rating" id="<?= $value['id'] ?>" >
        <input type="hidden" name="id" id="<?= $value['id'] ?>" value="<?php echo $value['id']?>"/>
        <input type="radio" name="example" class="rating" id="radio_1" value="1" />
        <input type="radio" name="example" class="rating" id="radio_2" value="2" />
        <input type="radio" name="example" class="rating" id="radio_3" value="3" />
        <input type="radio" name="example" class="rating" id="radio_4" value="4" />
        <input type="radio" name="example" class="rating" id="radio_5" value="5" />
    </section>
```
I have a hidden input here in the second line. How can i get the value of the hidden input in Javascript in current plugin's code when i click and rate?
