### ISSUE TITLE
"Star" and "stars" classes are too common

### ISSUE THREAD

**Issue by thekrotek** [irfan/jquery-star-rating#9]
I've found very minor issue with "star" and "stars" classes which your plugin uses. These are very common class names. For example, Joomla uses "star" class for mandatory fields in forms, which are marked with * character. If you load your plugin on a page with Joomla form, all mandatory fields will have star image beside * character.

I've changed "star" class to "rating-star" and "stars" to "rating-stars" in my copy of your plugin and would like to suggest you to do the same, since, I repeat, these are very common names.

**Comment by irfan** [comment]
Thanks for letting me know @thekrotek Just FYI, pull requests are very appreciated.

**Comment by thekrotek** [comment]
I honestly dunno, how to do PRs :-)

But I'd look into documentation, if this issue required PR. Just thought, a couple sentences would be enough.

**Comment by irfan** [comment]
I will try to change in the next version, but don't have time nowadays. Closing the issue.
